### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by ChrispaixK**
# UI for final capstone project
> In this milestone I added specific simple styles to components and pages

In this PR I :
- Update pages styles
- Update components styles
- Add responsiveness (Mobile view) 📱

### CODE REVIEW

**Review by benshidanny11 — CHANGES_REQUESTED** [review]
Hi @ChrispaixK  ✋ , 

_Great job so far 👏 💯 👍. However, there are a few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - The app's UI looks nice. 💯


## Required Changes ♻️
image

- [x] In UI, the Mobile breakpoint doesn't show the close icon so I can be able to hide the nav bar. Please resolve this issue.
image

- [x] Also When I click on the nav item, the close icon appears, But when I come back to the big screen the icon still shows. Please let's fix this too.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
  - [ ] Changing  [This file](https://github.com/ChrispaixK/car-valley-front-end/blob/6da038f3210acae0419e0fcba56cd2ce65ab2819/src/redux/store.jsx) to JS type as it's not a react component. Remember that every JSX file must be a React component.
  - [ ] Not using many Eslint disables as it makes code not look clean.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Ibizugbe — APPROVED** [review]
## Hi @ChrispaixK , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- The UI update feature looks very fantastic  ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ChrispaixK** [comment]
Thank you @Ibizugbe  and @benshidanny11 for your feedbacks
Let's work on @benshidanny11 requested changes before going to the next steps 🚀

**Comment by ChrispaixK** [comment]
Thanks, @benshidanny11 for collaborating to fix this, I think we can merge it now 🚀

**Review by benshidanny11 — APPROVED** [review]
Hi @ChrispaixK ,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

## Highlights
  - Follows git workflow.  💯
  - The codebase looks clean and professional. 💯 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**Pull request merged**
